version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=immo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=occulto
      - POSTGRES_PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/docker/volumes/PSQLdata/_data
  web:
    build: .
    volumes:
      - ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8080:8080"
    depends_on:
      - db
