version: "3.3"
services:
  db:
    image: postgres
    # image: 7evy/chocolate:db
    environment:
      - POSTGRES_DB=immo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=occulto
      - POSTGRES_PGDATA=/var/lib/postgresql/data
    ports:
      - "8082:8082"
    volumes:
      - /var/lib/docker/volumes/PSQLdata/_data
      - /var/run/postgresql/:/var/run/postgresql/
  init:
    volumes:
      - /var/run/postgresql/:/var/run/postgresql/
    command: python fill_db.py
    depends_on:
      - db
    image: 7evy/chocolate:init
  web:
    build: .
    volumes:
      - /var/run/postgresql/:/var/run/postgresql/
    # command: python manage.py runserver 0.0.0.0:8081
    command: sudo gunicorn web_app.wsgi:application -b localhost:8081
    ports:
      - 8081:8081
    depends_on:
      - db
      - init
    image: 7evy/chocolate:web
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - init
      - web
    image: 7evy/chocolate:nginx
