# Generated by Django 3.1.3 on 2020-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('pieces', models.SmallIntegerField(blank=True, null=True)),
                ('chambres', models.SmallIntegerField(blank=True, null=True)),
                ('loyer', models.SmallIntegerField(blank=True, null=True)),
                ('meuble', models.BooleanField(blank=True, null=True)),
                ('jardin', models.BooleanField(blank=True, null=True)),
                ('terrasse', models.BooleanField(blank=True, null=True)),
                ('dist_centre', models.SmallIntegerField(blank=True, null=True)),
                ('dist_transport', models.SmallIntegerField(blank=True, null=True)),
                ('dist_commerce', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'immo',
                'managed': False,
            },
        ),
    ]
