# Generated by Django 3.1.3 on 2020-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('vente_location', models.CharField(max_length=200)),
                ('surface', models.IntegerField(blank=True, null=True)),
                ('pièces', models.IntegerField(blank=True, null=True)),
                ('chambres', models.IntegerField(blank=True, null=True)),
                ('loyer', models.IntegerField(blank=True, null=True)),
                ('meublé', models.CharField(max_length=200)),
                ('jardin', models.CharField(max_length=200)),
                ('terrasse', models.CharField(max_length=200)),
                ('dist_centre', models.IntegerField(blank=True, null=True)),
                ('dist_transport', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chocolate_immo',
                'managed': False,
            },
        ),
    ]
