# Generated by Django 3.1.3 on 2020-11-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy_queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='immo',
            table='immo',
        ),
    ]
