# Generated by Django 3.1.3 on 2020-12-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy_queries', '0002_auto_20201127_1312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='immo',
            table='immo.db',
        ),
    ]
